//
// Created by Nicolas Reyland on 5/26/22.
//

#include <stddef.h>
#include "atom_type.h"

#define STRINGIFY_ATOM_TYPE_CASE(type) case type: { return #type; }

char * TOKEN_TYPE_STRING(TokenType type) {
    switch (type) {
        STRINGIFY_ATOM_TYPE_CASE(NONE_TOKEN)
        // Tokens
        STRINGIFY_ATOM_TYPE_CASE(OPERATOR_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(IO_NUMBER_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(TOKEN_TOKEN)
        // Specific 'Token' Tokens
        STRINGIFY_ATOM_TYPE_CASE(WORD_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(ASSIGNMENT_WORD_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(NAME_TOKEN)
        // Specific 'Word' Tokens
        STRINGIFY_ATOM_TYPE_CASE(BANG_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(OPENING_BRACKET_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(CLOSING_BRACKET_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(CASE_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DO_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DONE_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(ELIF_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(ELSE_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(ESAC_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(FI_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(FOR_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(IF_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(IN_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(THEN_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(UNTIL_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(WHILE_TOKEN)
        // Specific operator Tokens
        STRINGIFY_ATOM_TYPE_CASE(NEWLINE_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(AND_IF_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(OR_IF_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DSEMI_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DLESS_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DGREAT_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(LESSAND_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(GREATAND_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(LESSGREAT_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(DLESSDASH_TOKEN)
        STRINGIFY_ATOM_TYPE_CASE(CLOBBER_TOKEN)
        default:
            return NULL;
    }
}

char * PARSER_TYPE_STRING(ParserType type) {
    switch (type) {
        STRINGIFY_ATOM_TYPE_CASE(NONE_PARSER)
        // Grammar Parser
        STRINGIFY_ATOM_TYPE_CASE(PROGRAM_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(COMPLETE_COMMANDS_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(COMPLETE_COMMAND_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(LIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(AND_OR_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(PIPELINE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(PIPE_SEQUENCE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(COMMAND_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(COMPOUND_COMMAND_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SUBSHELL_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(COMPOUND_LIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(TERM_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(FOR_CLAUSE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(NAME_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(IN_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(WORDLIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CASE_CLAUSE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CASE_LIST_NS_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CASE_LIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CASE_ITEM_NS_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CASE_ITEM_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(PATTERN_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(IF_CLAUSE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(ELSE_PART_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(WHILE_CLAUSE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(UNTIL_CLAUSE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(FUNCTION_DEFINITION_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(FUNCTION_BODY_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(FNAME_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(BRACE_GROUP_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(DO_GROUP_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SIMPLE_COMMAND_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CMD_NAME_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CMD_WORD_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CMD_PREFIX_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CMD_SUFFIX_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(REDIRECT_LIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(IO_REDIRECT_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(IO_FILE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(FILENAME_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(IO_HERE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(HERE_END_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(NEWLINE_LIST_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(LINEBREAK_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEPARATOR_OP_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEPARATOR_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEQUENTIAL_SEP_PARSER)
        // Token Parser
        STRINGIFY_ATOM_TYPE_CASE(TK_WORD_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(TK_ASSIGNMENT_WORD_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(TK_NAME_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(TK_NEWLINE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(TK_IO_NUMBER_PARSER)
        // Generated Parsers
        STRINGIFY_ATOM_TYPE_CASE(GEN_STRING_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(GEN_STRING_R1_PARSER)
        // Abstract Combinator
        STRINGIFY_ATOM_TYPE_CASE(INVERTED_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEQUENCE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEQUENCE_PARSER_UNIT)
        STRINGIFY_ATOM_TYPE_CASE(REPETITION_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(CHOICE_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(OPTIONAL_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEPARATED_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(SEPARATED_REPETITION_PARSER)
        STRINGIFY_ATOM_TYPE_CASE(LOOKAHEAD_PARSER)
        // Generator Combinator
        STRINGIFY_ATOM_TYPE_CASE(GENERATOR_PARSER)
        default:
            return NULL;
    }
}
